### ISSUE TITLE
ModuleNotFoundError: No module named 'tools.visualchat_handler'

### ISSUE THREAD

**Issue by tonywut** [jasonaidm/ai_webui#2]
~/ai_webui$ python webui.py -c ./configs/webui_configs.yml
Traceback (most recent call last):
  File "/home6/wutuo/ai_webui/webui.py", line 4, in <module>
    from tools import AIWrapper
  File "/home6/wutuo/ai_webui/tools/__init__.py", line 6, in <module>
    from .ai_wrapper import AIWrapper
  File "/home6/wutuo/ai_webui/tools/ai_wrapper.py", line 3, in <module>
    from .visualchat_handler import VisualChatHandler
ModuleNotFoundError: No module named 'tools.visualchat_handler'

**Comment by night-ZK** [comment]
+1

**Comment by jasonaidm** [comment]
> ~/ai_webui$ python webui.py -c ./configs/webui_configs.yml Traceback (most recent call last): File "/home6/wutuo/ai_webui/webui.py", line 4, in from tools import AIWrapper File "/home6/wutuo/ai_webui/tools/**init**.py", line 6, in from .ai_wrapper import AIWrapper File "/home6/wutuo/ai_webui/tools/ai_wrapper.py", line 3, in from .visualchat_handler import VisualChatHandler ModuleNotFoundError: No module named 'tools.visualchat_handler'

**The bug has been resolved.**
