### ISSUE TITLE
Attempting to deserialize object on CUDA device 1 but torch.cuda.device_count() is 1

### ISSUE THREAD

**Issue by onezos** [jasonaidm/ai_webui#4]
`Traceback (most recent call last):
  File "D:\anaconda3\envs\aiwebui\Lib\site-packages\gradio\routes.py", line 442, in run_predict
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\aiwebui\Lib\site-packages\gradio\blocks.py", line 1392, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\aiwebui\Lib\site-packages\gradio\blocks.py", line 1097, in call_function
    prediction = await anyio.to_thread.run_sync(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\aiwebui\Lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\aiwebui\Lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "D:\anaconda3\envs\aiwebui\Lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\aiwebui\Lib\site-packages\gradio\utils.py", line 703, in wrapper
    response = f(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^
  File "F:\AI\webui\tools\ai_wrapper.py", line 76, in clip_video
    asr_result= self.whisper_handler.infer(audio_stream_file2)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\AI\webui\tools\whisper_handler.py", line 16, in infer
    self.init_model()
  File "F:\AI\webui\tools\whisper_handler.py", line 54, in init_model
    self.model = whisper.load_model(name=self.model_name, device=self.device, download_root=self.model_dir)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\aiwebui\Lib\site-packages\whisper\__init__.py", line 146, in load_model
    checkpoint = torch.load(fp, map_location=device)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\aiwebui\Lib\site-packages\torch\serialization.py", line 1014, in load
    raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
  File "D:\anaconda3\envs\aiwebui\Lib\site-packages\torch\serialization.py", line 1422, in _load
    unpickler.persistent_load = persistent_load
             ^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\aiwebui\Lib\site-packages\torch\serialization.py", line 1392, in persistent_load
    nbytes = numel * torch._utils._element_size(dtype)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\aiwebui\Lib\site-packages\torch\serialization.py", line 1366, in load_tensor
    typed_storage = torch.storage.TypedStorage(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\aiwebui\Lib\site-packages\torch\serialization.py", line 1296, in restore_location
    def restore_location(storage, location):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\aiwebui\Lib\site-packages\torch\serialization.py", line 381, in default_restore_location
    result = fn(storage, location)
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\aiwebui\Lib\site-packages\torch\serialization.py", line 274, in _cuda_deserialize
    device = validate_cuda_device(location)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anaconda3\envs\aiwebui\Lib\site-packages\torch\serialization.py", line 265, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on CUDA device '
RuntimeError: Attempting to deserialize object on CUDA device 1 but torch.cuda.device_count() is 1. Please use torch.load with map_location to map your storages to an existing device.`

**Comment by jasonaidm** [comment]
@onezos change "cuda:1" to "cuda:0" in base.yml file. (https://github.com/jasonaidm/ai_webui/blob/main/configs/base.yml)
